<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Derives a deterministic ordered list of 2–3 local image URLs for an event.
 *
 * No database, no network — pure function of the event UUID and type.
 * Same id always yields the same URLs (stable hash → pool indices).
 */
final class EventImageResolver
{
    /**
     * Total number of placeholder images in the pool.
     * Must equal the number of files generated by events:make-placeholders.
     */
    public const POOL_SIZE = 20;

    /**
     * Base URL path for pool images (relative to public/).
     */
    private const BASE_PATH = '/images/events/pool/';

    /**
     * File extension used for pool images and generated by events:make-placeholders.
     */
    private const EXTENSION = '.svg';

    /**
     * Return an ordered list of 2–3 local image URLs derived deterministically
     * from the event UUID.  The count and indices are a pure function of $id:
     * identical input always produces identical output.
     *
     * @return array<int, string> e.g. ['/images/events/pool/07.svg', '/images/events/pool/13.svg']
     */
    public static function for(string $id, string $type): array
    {
        // Hash both the UUID and the event type so that the type influences
        // which pool images are selected (type-coloured placeholder set).
        // md5 gives a well-distributed, platform-stable 32-char hex digest.
        $hash = md5($id.$type);

        // Extract three independent 16-bit segments from the hex digest so that
        // index selection is fully independent for each slot.
        // 4-nibble hex max = 65535, always fits in a PHP int — cast is safe.
        $seed1 = (int) hexdec(substr($hash, 0, 4));
        $seed2 = (int) hexdec(substr($hash, 4, 4));
        $seed3 = (int) hexdec(substr($hash, 8, 4));
        $seedCount = (int) hexdec(substr($hash, 12, 4));

        // 2 or 3 images — determined by the 4th segment.
        $count = ($seedCount % 2 === 0) ? 2 : 3;

        $size = self::POOL_SIZE;

        $index1 = $seed1 % $size;
        $index2 = $seed2 % $size;
        $index3 = $seed3 % $size;

        // Deduplicate while preserving order, then slice to $count.
        /** @var list<int> $indices */
        $indices = array_values(array_unique([$index1, $index2, $index3]));

        // If dedup collapsed indices we may have fewer than $count — scan
        // forward from the last chosen index to find the next free slot.
        // POOL_SIZE=20, max indices=3, so a free slot always exists.
        while (count($indices) < $count) {
            $candidate = ($indices[count($indices) - 1] + 1) % $size;
            while (in_array($candidate, $indices, true)) {
                $candidate = ($candidate + 1) % $size;
            }
            $indices[] = $candidate;
        }

        $indices = array_slice($indices, 0, $count);

        return array_map(
            static fn (int $i): string => self::BASE_PATH.str_pad((string) $i, 2, '0', STR_PAD_LEFT).self::EXTENSION,
            $indices,
        );
    }
}
